# -*- coding: utf-8 -*-
"""langchain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pTpnUCs3pYFGlZzAoe14CoIAZ-gecQOP
"""

!pip install openai
!pip install chromadb
!pip install tiktoken
!pip install pypdf

!pip install langchain

from langchain.chains import RetrievalQA
from langchain.llms import OpenAI
from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader("erasmus.pdf")
pages = loader.load_and_split()

from langchain.embeddings import OpenAIEmbeddings
embeddings = OpenAIEmbeddings(openai_api_key="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")
from langchain.vectorstores import Chroma
db = Chroma.from_documents(pages, embeddings)
retriever = db.as_retriever()
qa = RetrievalQA.from_chain_type(llm=OpenAI(openai_api_key="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"), chain_type="stuff", retriever=retriever)
query = "Entro quando scade il bando?"
qa.run(query)